package godot

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewCSGMeshFromPointer(ptr gdnative.Pointer) CSGMesh {
func newCSGMeshFromPointer(ptr gdnative.Pointer) CSGMesh {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := CSGMesh{}
	obj.SetBaseObject(owner)

	return obj
}

/*
Undocumented
*/
type CSGMesh struct {
	CSGPrimitive
	owner gdnative.Object
}

func (o *CSGMesh) BaseClass() string {
	return "CSGMesh"
}

/*
        Undocumented
	Args: [], Returns: void
*/
func (o *CSGMesh) X_MeshChanged() {
	//log.Println("Calling CSGMesh.X_MeshChanged()")

	// Build out the method's arguments
	ptrArguments := make([]gdnative.Pointer, 0, 0)

	// Get the method bind
	methodBind := gdnative.NewMethodBind("CSGMesh", "_mesh_changed")

	// Call the parent method.
	// void
	retPtr := gdnative.NewEmptyVoid()
	gdnative.MethodBindPtrCall(methodBind, o.GetBaseObject(), ptrArguments, retPtr)

}

/*
        Undocumented
	Args: [], Returns: Mesh
*/
func (o *CSGMesh) GetMesh() MeshImplementer {
	//log.Println("Calling CSGMesh.GetMesh()")

	// Build out the method's arguments
	ptrArguments := make([]gdnative.Pointer, 0, 0)

	// Get the method bind
	methodBind := gdnative.NewMethodBind("CSGMesh", "get_mesh")

	// Call the parent method.
	// Mesh
	retPtr := gdnative.NewEmptyObject()
	gdnative.MethodBindPtrCall(methodBind, o.GetBaseObject(), ptrArguments, retPtr)

	// If we have a return type, convert it from a pointer into its actual object.
	ret := newMeshFromPointer(retPtr)

	// Check to see if we already have an instance of this object in our Go instance registry.
	if instance, ok := InstanceRegistry.Get(ret.GetBaseObject().ID()); ok {
		return instance.(MeshImplementer)
	}

	// Check to see what kind of class this is and create it. This is generally used with
	// GetNode().
	className := ret.GetClass()
	if className != "Mesh" {
		actualRet := getActualClass(className, ret.GetBaseObject())
		return actualRet.(MeshImplementer)
	}

	return &ret
}

/*
        Undocumented
	Args: [{ false mesh Mesh}], Returns: void
*/
func (o *CSGMesh) SetMesh(mesh MeshImplementer) {
	//log.Println("Calling CSGMesh.SetMesh()")

	// Build out the method's arguments
	ptrArguments := make([]gdnative.Pointer, 1, 1)
	ptrArguments[0] = gdnative.NewPointerFromObject(mesh.GetBaseObject())

	// Get the method bind
	methodBind := gdnative.NewMethodBind("CSGMesh", "set_mesh")

	// Call the parent method.
	// void
	retPtr := gdnative.NewEmptyVoid()
	gdnative.MethodBindPtrCall(methodBind, o.GetBaseObject(), ptrArguments, retPtr)

}

// CSGMeshImplementer is an interface that implements the methods
// of the CSGMesh class.
type CSGMeshImplementer interface {
	CSGPrimitiveImplementer
	X_MeshChanged()
	GetMesh() MeshImplementer
	SetMesh(mesh MeshImplementer)
}
