package godot

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewPluginScriptFromPointer(ptr gdnative.Pointer) PluginScript {
func newPluginScriptFromPointer(ptr gdnative.Pointer) PluginScript {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := PluginScript{}
	obj.SetBaseObject(owner)

	return obj
}

/*
Undocumented
*/
type PluginScript struct {
	Script
	owner gdnative.Object
}

func (o *PluginScript) BaseClass() string {
	return "PluginScript"
}

/*
        Undocumented
	Args: [], Returns: Object
*/
func (o *PluginScript) New() ObjectImplementer {
	//log.Println("Calling PluginScript.New()")

	// Build out the method's arguments
	ptrArguments := make([]gdnative.Pointer, 0, 0)

	// Get the method bind
	methodBind := gdnative.NewMethodBind("PluginScript", "new")

	// Call the parent method.
	// Object
	retPtr := gdnative.NewEmptyObject()
	gdnative.MethodBindPtrCall(methodBind, o.GetBaseObject(), ptrArguments, retPtr)

	// If we have a return type, convert it from a pointer into its actual object.
	ret := newObjectFromPointer(retPtr)

	// Check to see if we already have an instance of this object in our Go instance registry.
	if instance, ok := InstanceRegistry.Get(ret.GetBaseObject().ID()); ok {
		return instance.(ObjectImplementer)
	}

	// Check to see what kind of class this is and create it. This is generally used with
	// GetNode().
	className := ret.GetClass()
	if className != "Object" {
		actualRet := getActualClass(className, ret.GetBaseObject())
		return actualRet.(ObjectImplementer)
	}

	return &ret
}

// PluginScriptImplementer is an interface that implements the methods
// of the PluginScript class.
type PluginScriptImplementer interface {
	ScriptImplementer
	New() ObjectImplementer
}
