package godot

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewResourceFormatLoaderNativeScriptFromPointer(ptr gdnative.Pointer) ResourceFormatLoaderNativeScript {
func newResourceFormatLoaderNativeScriptFromPointer(ptr gdnative.Pointer) ResourceFormatLoaderNativeScript {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := ResourceFormatLoaderNativeScript{}
	obj.SetBaseObject(owner)

	return obj
}

/*

 */
type ResourceFormatLoaderNativeScript struct {
	ResourceFormatLoader
	owner gdnative.Object
}

func (o *ResourceFormatLoaderNativeScript) BaseClass() string {
	return "ResourceFormatLoaderNativeScript"
}

// ResourceFormatLoaderNativeScriptImplementer is an interface that implements the methods
// of the ResourceFormatLoaderNativeScript class.
type ResourceFormatLoaderNativeScriptImplementer interface {
	ResourceFormatLoaderImplementer
}
