package godot

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewResourceFormatLoaderDynamicFontFromPointer(ptr gdnative.Pointer) ResourceFormatLoaderDynamicFont {
func newResourceFormatLoaderDynamicFontFromPointer(ptr gdnative.Pointer) ResourceFormatLoaderDynamicFont {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := ResourceFormatLoaderDynamicFont{}
	obj.SetBaseObject(owner)

	return obj
}

/*

 */
type ResourceFormatLoaderDynamicFont struct {
	ResourceFormatLoader
	owner gdnative.Object
}

func (o *ResourceFormatLoaderDynamicFont) BaseClass() string {
	return "ResourceFormatLoaderDynamicFont"
}

// ResourceFormatLoaderDynamicFontImplementer is an interface that implements the methods
// of the ResourceFormatLoaderDynamicFont class.
type ResourceFormatLoaderDynamicFontImplementer interface {
	ResourceFormatLoaderImplementer
}
