package godot

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewResourceFormatDDSFromPointer(ptr gdnative.Pointer) ResourceFormatDDS {
func newResourceFormatDDSFromPointer(ptr gdnative.Pointer) ResourceFormatDDS {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := ResourceFormatDDS{}
	obj.SetBaseObject(owner)

	return obj
}

/*

 */
type ResourceFormatDDS struct {
	ResourceFormatLoader
	owner gdnative.Object
}

func (o *ResourceFormatDDS) BaseClass() string {
	return "ResourceFormatDDS"
}

// ResourceFormatDDSImplementer is an interface that implements the methods
// of the ResourceFormatDDS class.
type ResourceFormatDDSImplementer interface {
	ResourceFormatLoaderImplementer
}
