package godot

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewResourceFormatLoaderShaderFromPointer(ptr gdnative.Pointer) ResourceFormatLoaderShader {
func newResourceFormatLoaderShaderFromPointer(ptr gdnative.Pointer) ResourceFormatLoaderShader {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := ResourceFormatLoaderShader{}
	obj.SetBaseObject(owner)

	return obj
}

/*

 */
type ResourceFormatLoaderShader struct {
	ResourceFormatLoader
	owner gdnative.Object
}

func (o *ResourceFormatLoaderShader) BaseClass() string {
	return "ResourceFormatLoaderShader"
}

// ResourceFormatLoaderShaderImplementer is an interface that implements the methods
// of the ResourceFormatLoaderShader class.
type ResourceFormatLoaderShaderImplementer interface {
	ResourceFormatLoaderImplementer
}
