package godot

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewResourceFormatLoaderTheoraFromPointer(ptr gdnative.Pointer) ResourceFormatLoaderTheora {
func newResourceFormatLoaderTheoraFromPointer(ptr gdnative.Pointer) ResourceFormatLoaderTheora {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := ResourceFormatLoaderTheora{}
	obj.SetBaseObject(owner)

	return obj
}

/*

 */
type ResourceFormatLoaderTheora struct {
	ResourceFormatLoader
	owner gdnative.Object
}

func (o *ResourceFormatLoaderTheora) BaseClass() string {
	return "ResourceFormatLoaderTheora"
}

// ResourceFormatLoaderTheoraImplementer is an interface that implements the methods
// of the ResourceFormatLoaderTheora class.
type ResourceFormatLoaderTheoraImplementer interface {
	ResourceFormatLoaderImplementer
}
