package godot

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewResourceFormatPKMFromPointer(ptr gdnative.Pointer) ResourceFormatPKM {
func newResourceFormatPKMFromPointer(ptr gdnative.Pointer) ResourceFormatPKM {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := ResourceFormatPKM{}
	obj.SetBaseObject(owner)

	return obj
}

/*

 */
type ResourceFormatPKM struct {
	ResourceFormatLoader
	owner gdnative.Object
}

func (o *ResourceFormatPKM) BaseClass() string {
	return "ResourceFormatPKM"
}

// ResourceFormatPKMImplementer is an interface that implements the methods
// of the ResourceFormatPKM class.
type ResourceFormatPKMImplementer interface {
	ResourceFormatLoaderImplementer
}
