package godot

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewResourceFormatLoaderImageFromPointer(ptr gdnative.Pointer) ResourceFormatLoaderImage {
func newResourceFormatLoaderImageFromPointer(ptr gdnative.Pointer) ResourceFormatLoaderImage {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := ResourceFormatLoaderImage{}
	obj.SetBaseObject(owner)

	return obj
}

/*

 */
type ResourceFormatLoaderImage struct {
	ResourceFormatLoader
	owner gdnative.Object
}

func (o *ResourceFormatLoaderImage) BaseClass() string {
	return "ResourceFormatLoaderImage"
}

// ResourceFormatLoaderImageImplementer is an interface that implements the methods
// of the ResourceFormatLoaderImage class.
type ResourceFormatLoaderImageImplementer interface {
	ResourceFormatLoaderImplementer
}
