package godot

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewResourceFormatPVRFromPointer(ptr gdnative.Pointer) ResourceFormatPVR {
func newResourceFormatPVRFromPointer(ptr gdnative.Pointer) ResourceFormatPVR {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := ResourceFormatPVR{}
	obj.SetBaseObject(owner)

	return obj
}

/*

 */
type ResourceFormatPVR struct {
	ResourceFormatLoader
	owner gdnative.Object
}

func (o *ResourceFormatPVR) BaseClass() string {
	return "ResourceFormatPVR"
}

// ResourceFormatPVRImplementer is an interface that implements the methods
// of the ResourceFormatPVR class.
type ResourceFormatPVRImplementer interface {
	ResourceFormatLoaderImplementer
}
