package godot

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewResourceFormatLoaderVideoStreamGDNativeFromPointer(ptr gdnative.Pointer) ResourceFormatLoaderVideoStreamGDNative {
func newResourceFormatLoaderVideoStreamGDNativeFromPointer(ptr gdnative.Pointer) ResourceFormatLoaderVideoStreamGDNative {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := ResourceFormatLoaderVideoStreamGDNative{}
	obj.SetBaseObject(owner)

	return obj
}

/*
Undocumented
*/
type ResourceFormatLoaderVideoStreamGDNative struct {
	ResourceFormatLoader
	owner gdnative.Object
}

func (o *ResourceFormatLoaderVideoStreamGDNative) BaseClass() string {
	return "ResourceFormatLoaderVideoStreamGDNative"
}

// ResourceFormatLoaderVideoStreamGDNativeImplementer is an interface that implements the methods
// of the ResourceFormatLoaderVideoStreamGDNative class.
type ResourceFormatLoaderVideoStreamGDNativeImplementer interface {
	ResourceFormatLoaderImplementer
}
