package godot

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewResourceFormatLoaderWebmFromPointer(ptr gdnative.Pointer) ResourceFormatLoaderWebm {
func newResourceFormatLoaderWebmFromPointer(ptr gdnative.Pointer) ResourceFormatLoaderWebm {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := ResourceFormatLoaderWebm{}
	obj.SetBaseObject(owner)

	return obj
}

/*

 */
type ResourceFormatLoaderWebm struct {
	ResourceFormatLoader
	owner gdnative.Object
}

func (o *ResourceFormatLoaderWebm) BaseClass() string {
	return "ResourceFormatLoaderWebm"
}

// ResourceFormatLoaderWebmImplementer is an interface that implements the methods
// of the ResourceFormatLoaderWebm class.
type ResourceFormatLoaderWebmImplementer interface {
	ResourceFormatLoaderImplementer
}
