package godot

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewResourceFormatLoaderBinaryFromPointer(ptr gdnative.Pointer) ResourceFormatLoaderBinary {
func newResourceFormatLoaderBinaryFromPointer(ptr gdnative.Pointer) ResourceFormatLoaderBinary {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := ResourceFormatLoaderBinary{}
	obj.SetBaseObject(owner)

	return obj
}

/*

 */
type ResourceFormatLoaderBinary struct {
	ResourceFormatLoader
	owner gdnative.Object
}

func (o *ResourceFormatLoaderBinary) BaseClass() string {
	return "ResourceFormatLoaderBinary"
}

// ResourceFormatLoaderBinaryImplementer is an interface that implements the methods
// of the ResourceFormatLoaderBinary class.
type ResourceFormatLoaderBinaryImplementer interface {
	ResourceFormatLoaderImplementer
}
