package godot

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewTranslationLoaderPOFromPointer(ptr gdnative.Pointer) TranslationLoaderPO {
func newTranslationLoaderPOFromPointer(ptr gdnative.Pointer) TranslationLoaderPO {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := TranslationLoaderPO{}
	obj.SetBaseObject(owner)

	return obj
}

/*

 */
type TranslationLoaderPO struct {
	ResourceFormatLoader
	owner gdnative.Object
}

func (o *TranslationLoaderPO) BaseClass() string {
	return "TranslationLoaderPO"
}

// TranslationLoaderPOImplementer is an interface that implements the methods
// of the TranslationLoaderPO class.
type TranslationLoaderPOImplementer interface {
	ResourceFormatLoaderImplementer
}
